# Computing the state-value of $4\times 4$ Gridworld, Example 4.1, page 76

Here, we compute the state-value function via direct approach, not using DP based on optimality equations.

In [119]:
import numpy as np 

In [120]:
M = np.zeros((15,15))
G = np.arange(16).reshape(4,4)
G[3,3] = 0
H = np.zeros((6,6))
H[1:5,1:5] = G
H[0] = H[1]
H[5] = H[4]
H[1:5, 0] = H[1:5, 1]
H[1:5, 5] = H[1:5, 4]
H = H.astype(int)
H

array([[ 0,  0,  1,  2,  3,  0],
       [ 0,  0,  1,  2,  3,  3],
       [ 4,  4,  5,  6,  7,  7],
       [ 8,  8,  9, 10, 11, 11],
       [12, 12, 13, 14,  0,  0],
       [ 0, 12, 13, 14,  0,  0]])

In [121]:
for i in range(1,5):
    for j in range(1,5):

        M[H[i,j],H[i+1,j]] += 1 
        M[H[i,j],H[i-1,j]] += 1 
        M[H[i,j],H[i,j+1]] += 1
        M[H[i,j],H[i,j-1]] += 1

In [122]:
M

array([[4., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 2., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 2., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0.

In [123]:
M[0]*=0 
M/=4

In [124]:

M.sum(axis = 1)

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [125]:
M

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.25, 0.25, 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.5 , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.  , 0.  , 0.  , 0.25, 0.25, 0.  , 0.  , 0.25, 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.25, 0.  ,
        0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.25,
        0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.25, 0.  , 0.  , 0.  ,
        0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.25, 0.25, 0.  ,
        0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  ,

In [131]:
sum = np.zeros((15,15))
temp = M.copy()
for i in range(1,1000):
    sum += i * temp
    temp = temp @ M

In [132]:
sum

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [14.        , 14.67845067, 21.44828523, 23.36734694, 12.50498128,
        17.52662722, 20.04081633, 20.1435515 , 17.3564485 , 17.95918367,
        16.47337278, 12.99501872, 18.63265306, 17.05171477, 11.82154933],
       [20.        , 21.44828523, 33.05850743, 37.70918367, 17.3564485 ,
        25.02810651, 30.55102041, 31.93128849, 24.06871151, 25.44897959,
        24.47189349, 20.1435515 , 25.79081633, 23.94149257, 17.05171477],
       [22.        , 23.36734694, 37.70918367, 44.92346939, 18.63265306,
        27.25      , 34.40816327, 37.70918367, 25.79081633, 27.59183673,
        27.25      , 23.36734694, 27.57653061, 25.79081633, 18.63265306],
       [14.        , 12.50498128, 17.3564485 , 18.63265306, 14.67845067,
        17.52662722, 17.95918367, 17.05171477, 

In [133]:
sum[:,0]

array([ 0., 14., 20., 22., 14., 18., 20., 20., 20., 20., 18., 14., 22.,
       20., 14.])